### ISSUE TITLE
Output for all files is "sourceMap for undefined uploaded to newrelic", source maps are not uploaded

### ISSUE THREAD

**Issue by jamiev-img** [1stdibs/new-relic-source-map-webpack-plugin#9]
I've tracked the issue down to [uploadSourceMap.js#L19](https://github.com/1stdibs/new-relic-source-map-webpack-plugin/blob/fef3a0a7c89473c1ecf6cb210394bf30ee36c156/src/uploadSourceMap.js#L19), where `fileObj.children` is always undefined, because `fileObj` is an instance of `SizeOnlySource`.

I'm using webpack version 4.29.0.

**Comment by ovidijusr** [comment]
Got the same issue

I'm using webpack version 4.29.3

**Comment by marr** [comment]
It appears that this fix hasn't been published to NPM yet.

**Comment by kostasmanionis** [comment]
Might be fixed with `v1.2.0`. Closing.
